# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{svdrpd}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Denis Knauf"]
  s.date = %q{2010-02-26}
  s.default_executable = %q{svdrpd}
  s.description = %q{Allowes to more than one connection to communicate with VDR}
  s.email = %q{Denis.Knauf@gmail.com}
  s.executables = ["svdrpd"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "VERSION",
     "bin/svdrpd"
  ]
  s.homepage = %q{http://github.com/DenisKnauf/svdrpd}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["bin"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Multiplexer for SVDRP}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<select>, [">= 0"])
    else
      s.add_dependency(%q<select>, [">= 0"])
    end
  else
    s.add_dependency(%q<select>, [">= 0"])
  end
end

